apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisaccts
spec:
  selector: 
    matchLabels:
      app: redisaccts
  template:
    metadata:
      labels:
        app: redisaccts
    spec:
      containers:
        - name: redis
          image: 'bitnami/redis'
          ports:
            - containerPort: 6379

      volumes:
        - name: redis-volume
          configMap:
            name: redis-config
            items:
              - key: env
                path: .env
