apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfk8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      containers:
      - name: classroom-api
        image: tfk8scloud/classroom-srv
        ports:
        - containerPort: 80