apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfk8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-srv
  template:
    metadata:
      labels:
        app: accounts-srv
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: accounts-api
        image: tfk8scloud/accounts-srv:latest
        ports:
        - containerPort: 8080
          volumeMounts:
            - name: accounts-volume
              mountPath: /home/node/app/.env
              subPath: .env

      volumes:
        - name: accounts-volume
          configMap:
            name: accounts-config
            items:
              - key: env
                path: .env
